?load
load("GOLFdata.RData")
head(total09)
dim(total09)
class(total09)
?pairs
pairs(total09)
?cor
attach(total09)
cor(SCORE,EARN)
cor(GIR,EARN)
?lm
?formula
R1<-lm(formula=EARN~SCORE+GIR,data=total09)
summary(R1)
vcov(R1)
res<-residuals(R1)
resid[which(resid==max(res))]
detach(total09)
